version: 2

project_name: spotdb
builds:
  - main: .
    binary: spotdb
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

homebrew_casks:
  - name: spotdb
    repository:
      owner: aliengiraffe
      name: homebrew-spaceship
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    description: "SpotDB - A fast, lightweight data analysis tool"
    homepage: "https://github.com/aliengiraffe/spotdb"
    license: "MIT"
    caveats: |
      SpotDB is a command-line tool for data analysis.
      Run 'spotdb -version' to verify installation.
    binary: spotdb