version: 2

project_name: spotdb
builds:
  - env: 
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc

homebrew_casks:
  - name: spotdb
    repository:
      owner: aliengiraffe
      name: homebrew-spaceship
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    description: "SpotDB - A fast, lightweight data analysis tool"
    homepage: "https://github.com/aliengiraffe/spotdb"
    license: "MIT"
    caveats: |
      SpotDB is a command-line tool for data analysis.
      Run 'spotdb -version' to verify installation.
    binary: spotdb