version: 2

project_name: spotdb
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64