version: 2

project_name: spotdb
builds:
  - id: linux-amd64
    env: [CGO_ENABLED=1]
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -s -w
  - id: linux-arm64
    env: [CGO_ENABLED=1]
    goos: [linux]
    goarch: [arm64]
    ldflags:
      - -s -w
  - id: darwin-amd64
    env: [CGO_ENABLED=1]
    goos: [darwin]
    goarch: [amd64]
    ldflags:
      - -s -w
  - id: darwin-arm64
    env: [CGO_ENABLED=1]
    goos: [darwin]
    goarch: [arm64]
    ldflags:
      - -s -w

homebrew_casks:
  - name: spotdb
    repository:
      owner: aliengiraffe
      name: homebrew-spaceship
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    description: "SpotDB - A fast, lightweight data analysis tool"
    homepage: "https://github.com/aliengiraffe/spotdb"
    license: "MIT"
    caveats: |
      SpotDB is a command-line tool for data analysis.
      Run 'spotdb -version' to verify installation.
    binary: spotdb