version: 2

project_name: spotdb
builds:
  - main: .
    binary: spotdb
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

homebrew_casks:
  - name: spotdb
    repository:
      owner: aliengiraffe
      name: homebrew-spaceship
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    description: "SpotDB - A fast, lightweight data analysis tool"
    homepage: "https://github.com/aliengiraffe/spotdb"
    license: "MIT"
    caveats: |
      SpotDB is a command-line tool for data analysis.
      Run 'spotdb -version' to verify installation.
    binary: spotdb